#!/bin/sh

# Set default start/boot
#-----------------------

logger -p local6.notice -t installer "app-firewall-core - enabling firewall"
/sbin/chkconfig --add firewall >/dev/null 2>&1
/sbin/chkconfig firewall on >/dev/null 2>&1
